disabled_rules:
  - identifier_name
  - line_length
included: # paths to include during linting. `--path` is ignored if present.
  - PRESTO-Wallet
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
reporter: "xcode"
